#
#  1. Check we can parse gt3x v2 file without error
#  2. Test if the extracted epoch files have changed
#
name: gt3x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  parsing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile Parser
        run: javac -cp java/JTransforms-3.1-with-dependencies.jar java/*.java

      - name: Parse gt3x V2 file
        run: |
          cd java
          java AccelerometerParser Tests/Resources/sampleV2.gt3x npyOutput:True  rawOutput:True timeZone:Brazil/West
          java AccelerometerParser Tests/Resources/gt3xV1.gt3x npyOutput:True  rawOutput:True timeZone:Brazil/West

      - name: compare epoch output
        uses: tianhaoz95/mirror-action@v1.0.1
        with:
          original: "java/Tests/Resources/sampleV2EpochRef.csv"
          mirror: "java/Tests/Resources/sampleV2Epoch.csv"

      - name: compare epoch output
        uses: tianhaoz95/mirror-action@v1.0.1
        with:
          original: "java/Tests/Resources/gt3xV1EpochRef.csv"
          mirror: "java/Tests/Resources/gt3xV1Epoch.csv"
            